services:
  campeonatoapp:
    image: campeonatoimg:latest
    build: .
    ports:
      - "3006:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: